name: globo-deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Obter código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./src

      - name: Validação
        run: terraform validate
        working-directory: ./src
      
      - name: Planejamento
        run: terraform plan -out=tfplan
        working-directory: ./src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload do plano para uso posterior
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ./src/tfplan

  terraform-apply:
    name: Terraform Apply (Aguardando Autorização)
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Obter código
        uses: actions/checkout@v3

      - name: Baixar o plano gerado
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ./src

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./src

      - name: Aplicar Mudanças (Terraform Apply)
        run: terraform apply -auto-approve tfplan
        working-directory: ./src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Mesclar mudanças da develop para main
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge develop --no-ff -m "Merge develop into main [skip ci]"
          git push origin main